### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mxnmnm** [Leviathan-Studio/CraftStudioAPI#33]
## Expected Behavior

Regular memory usage, characters/strings/variables/integers should be using up the most memory
## Current Behavior

com.mia.craftstudioapi.libgdx.Vector3 is constantly making copies of itself without deleting the previous vector 3s (on a side note, there is another memory leak but I'm not sure what's causing it so if you can tell me which mod is causing it so I can report it to that mod author or remove the mod, that would be great)
## Possible Solution

Maybe make the vector 3s delete themselves after a while?  I'm not sure.

## Steps to Reproduce 

1. I think it's something in my world but I'm not sure what it is.  I did try to make a new world and the tps was fine (a bit high) but fine
2. 
3.
4.

## Context

Anything that puts any form of pressure on the server (builder from rf tools) causes me or anyone else on to time out.
Makes multiple people joining nearly unplayable.
Heavily built in world which I can send if needed along with all of the mods.

## Crash Report

I have a link to a heap dump, if that isn't good enough let me know what else you need.
https://drive.google.com/open?id=1HaSvpqTcDMszEhvnHmh7YiJ5psBiqjg9

## Your Environment

* Version of the api used: 
0.3.0.87
* Version of forge used: 
12.18.3.2511
* Link to your project:

**Comment by Timmypote** [comment]
I'm not sure what your are talking about because:
- I'm pretty sure this class doesn't belong to the api: "com.mia.craftstudioapi.libgdx.Vector3"
You should look for the mods that own the "com.mia" package.
- Memory leak are almost impossible in Java, but your problem id probably due to an overload of the garbage collector.
- As you have other mods you should add the list in the "Your Environment" part.
To sumerise, probably not our fault but send your mods list, so I can see were it come from :)

**Comment by mxnmnm** [comment]
I just decided to send all of the mods directly because it would be a bit more time efficient and you'd get the most info out of it.  So here's the link https://drive.google.com/open?id=1AVx9ibgXDEJEebNtNfE_0E6vX8atxyl5

**Comment by mxnmnm** [comment]
Alright so I figured out one of the issues was with decocraft so help figuring out where the second memory leak would be very useful.  Thanks for helping me!

**Comment by Timmypote** [comment]
Sorry for the late answer.
I checked and I think your problem come from the mod Decocraft, as you've said. The CraftStudioApi has nothing to do with Decocraft, so I can't help you. You should go and ask the author of Decocraft.

**Comment by Timmypote** [comment]
Sorry for the late answer.
I checked and I think your problem come from the mod Decocraft, as you've said. The CraftStudioApi has nothing to do with Decocraft, so I can't help you. You should go and ask the author of Decocraft.
