### ISSUE TITLE
Fix maven repository (error 500)

### ISSUE THREAD

**Issue by ArisuOngaku** [Leviathan-Studio/CraftStudioAPI#37]
The recommended maven repository in the Wiki is broken. It gives a 500 error code.

## Expected Behavior

The maven repository should be up and running fine, delivering CraftStudioApi's artifacts.

## Current Behavior

Browsing http://maven.leviathan-studio.com/artifactory/leviathan/com/leviathanstudio/CraftStudio/ gives this JSON response :
```JSON
{
  "errors" : [ {
    "status" : 500,
    "message" : "HTTP response status 500:Failed on executing /api/v1/auth/login, with response: {\n  \"errors\" : [ {\n    \"code\" : \"INTERNAL_SERVER_ERROR\",\n    \"message\" : \"Could not update login details for user 'anonymous'\",\n    \"detail\" : \"An SQL data change is not permitted for a read-only connection, user or database.\"\n  } ]\n}"
  } ]
}
```
Using the provided build.gradle dependency code doesn't resolve it.

## Possible Solution

An alternative could be recommanding the use of the `jitpack.io` maven repository.
(See https://jitpack.io/#Leviathan-Studio/CraftStudioAPI)

## Steps to Reproduce 

Just follow https://github.com/Leviathan-Studio/CraftStudioAPI/wiki/Add-the-API-to-your-project

## Your Environment

* Version of the api used: 0.3.0.86-mc1.11.2-beta-dev
* Version of forge used: 1.12.2-14.23.2.2611

**Comment by ZeAmateis** [comment]
Hi !

We're planning to an alternative like you say, so, stay tuned ! :)
And thank you for the issue.

You can come on the discord, if you want to directly interact with the staff or other people !

**Comment by Phenix246** [comment]
I fix the maven but I'm looking for an other solution. Free to you to propose some.
