### ISSUE TITLE
Random CME when rendering lot's of entities

### ISSUE THREAD

**Issue by Timmypote** [Leviathan-Studio/CraftStudioAPI#40]
## Expected Behavior

The entities should render without exception.

## Current Behavior

A ConcurentModificationException can be raised, when rendering entities.

## Steps to Reproduce 

1. Summon a lot of custom entities.
2. Wait.

## Crash Report

https://pastebin.com/f4XbcCGr

## Your Environment

* Version of the api used: 1.0.0.93-alpha

(Thanks to mcpecommander for repporting it on discord)

**Comment by Phenix246** [comment]
Fix en 1.0.1.95-alpha
